# Makefile.toml

[tasks.build-client]
cwd = "./client/"
command = "cargo"
args = ["make", "all"]

[tasks.build-server]
cwd = "./server/"
command = "cargo"
args = ["make", "podman-image"]

[tasks.server-run]
description = "Lancement du serveur."
command = "podman"
args = ["run", "--replace", "--name", "server", "-ti", "--detach", "--rm", "--publish", "3000:3000", "--network=host", "mpatron/server:latest"]
dependencies = ["build-client", "build-server"]

[tasks.all]
description = "Exécute toutes les tâches."
# command = "./client/target/debug/client"
command = "curl"
args = ["http://localhost:3000"]
dependencies = ["server-run"]

[tasks.default]
alias = "all"

# sudo sed -i "s/^bind-address.*/bind-address=0.0.0.0/g" "/etc/mysql/mariadb.conf.d/50-server.cnf"